exercises/hello-world/.gitignore
exercises/hello-world/README.md
exercises/hello-world/__tests__/HelloWorld_test.re
exercises/hello-world/bsconfig.json
exercises/hello-world/package-lock.json
exercises/hello-world/package.json
exercises/hello-world/src/HelloWorld.re

Here's a first draft of the `hello-world` exercise. #1 
Tasks: (add more as required)

Hello ReasonML

---

.gitignore
README.md
config.json
docs/ABOUT.md
docs/INSTALLATION.md
docs/LEARNING.md
docs/RESOURCES.md
docs/TESTS.md
exercises/leap/README.md
exercises/leap/__tests__/Leap_test.re
exercises/leap/bsconfig.json
exercises/leap/package.json
exercises/leap/src/Leap.re
exercises/space-age/__tests__/Space_age_test.re
exercises/space-age/bsconfig.json
exercises/space-age/package.json
exercises/space-age/src/Space_age.re

Add two of the easier exercise.
Make a start on the docs/

Add leap and space age

---

bin/new-exercise.sh
template/bsconfig.json
template/package.json

Script to make creating a new blank exercise quicker.

Add template exercise

---

config.json
exercises/word-count/README.md
exercises/word-count/__tests__/WordCount_test.re
exercises/word-count/bsconfig.json
exercises/word-count/package-lock.json
exercises/word-count/package.json
exercises/word-count/src/Example.re

Just to let you know that I'm working on it

added word-count exercise

---

config.json
exercises/phone-number/.gitignore
exercises/phone-number/README.md
exercises/phone-number/__tests__/PhoneNumber_test.re
exercises/phone-number/bsconfig.json
exercises/phone-number/package-lock.json
exercises/phone-number/package.json
exercises/phone-number/src/Example.re

~~Just to let you know that I'm working on it.~~

phone number exercise

---

.gitignore
Makefile
exercises/anagram/src/Anagram.rei
exercises/anagram/src/Example.re
exercises/binary-search/src/BinarySearch.rei
exercises/bob/src/Bob.rei
exercises/change/src/Change.rei
exercises/change/src/Example.re
exercises/hello-world/src/HelloWorld.rei
exercises/leap/src/Leap.rei
exercises/pangram/src/Pangram.rei
exercises/phone-number/src/PhoneNumber.rei
exercises/raindrops/src/Raindrops.rei
exercises/rna-transcription/src/Example.re
exercises/rna-transcription/src/RnaTranscription.rei
exercises/run-length-encoding/src/RunLengthEncoding.rei
exercises/space-age/__tests__/SpaceAge_test.re
exercises/space-age/src/Example.re
exercises/space-age/src/SpaceAge.rei
exercises/word-count/src/WordCount.rei

Closes #33 
* Add interface files for all existing exercises 
* Makefile changes to use the interface files in CI tests

Add reason interface files for all exercises

---

config.json
exercises/armstrong-numbers/README.md
exercises/armstrong-numbers/__tests__/ArmstrongNumbers_test.re
exercises/armstrong-numbers/bsconfig.json
exercises/armstrong-numbers/package-lock.json
exercises/armstrong-numbers/package.json
exercises/armstrong-numbers/src/ArmstrongNumbers.rei
exercises/armstrong-numbers/src/Example.re

Canonical data: https://github.com/exercism/problem-specifications/tree/master/exercises/armstrong-numbers

Add armstrong-numbers exercise

---

config.json

Looking at https://exercism.io/my/tracks/reasonml
The number of core exercises vs optional is a bit unbalanced towards core, so reducing the number of core exercises.

Reduce the number of core exercises.

---

README.md
exercises/accumulate/package-lock.json
exercises/acronym/package-lock.json
exercises/all-your-base/package-lock.json
exercises/allergies/package-lock.json
exercises/anagram/package-lock.json
exercises/armstrong-numbers/package-lock.json
exercises/binary-search/package-lock.json
exercises/bob/package-lock.json
exercises/change/package-lock.json
exercises/hello-world/package-lock.json
exercises/isogram/package-lock.json
exercises/leap/package-lock.json
exercises/minesweeper/package-lock.json
exercises/pangram/package-lock.json
exercises/phone-number/package-lock.json
exercises/protein-translation/package-lock.json
exercises/raindrops/package-lock.json
exercises/rna-transcription/package-lock.json
exercises/roman-numerals/package-lock.json
exercises/run-length-encoding/package-lock.json
exercises/space-age/package-lock.json
exercises/word-count/package-lock.json
package-lock.json

* Fix ReasonML installation link in README.
* Other minor touchups to README.
* Sync `package-lock.json`.

Minor README fixes and files sync

---

exercises/bob/README.md
exercises/bob/__tests__/Bob_test.re

1. One missing spec: `non-letters with question`
2. Minor wording changes for test descriptions
3. Clarifications in README: https://github.com/exercism/problem-specifications/pull/1516

Update README & tests for bob exercise

---

config.json
exercises/two-fer/README.md
exercises/two-fer/__tests__/TwoFer_test.re
exercises/two-fer/bsconfig.json
exercises/two-fer/package-lock.json
exercises/two-fer/package.json
exercises/two-fer/src/Example.re
exercises/two-fer/src/TwoFer.rei

Implement two-fer exercise

---

config.json
exercises/resistor-color/README.md
exercises/resistor-color/__tests__/ResistorColor_test.re
exercises/resistor-color/bsconfig.json
exercises/resistor-color/package-lock.json
exercises/resistor-color/package.json
exercises/resistor-color/src/Example.re
exercises/resistor-color/src/ResistorColor.rei

Implement resistor-color exercise

---

config.json

Closes https://github.com/exercism/reasonml/issues/118
Closes https://github.com/exercism/reasonml/issues/119
Closes https://github.com/exercism/reasonml/issues/120
Parent launch issue: https://github.com/exercism/reasonml/issues/127

Launch steps [part 1]

---

exercises/practice/accumulate/.meta/config.json
exercises/practice/acronym/.meta/config.json
exercises/practice/all-your-base/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/binary-search/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/change/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/isogram/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/minesweeper/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/protein-translation/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/resistor-color/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/two-fer/.meta/config.json
exercises/practice/word-count/.meta/config.json

To help tracks define the files in the exercise's `.meta/config.json` file, we've added support for defining these file patterns in the track's `config.json` file. See [this PR](https://github.com/exercism/docs/pull/58).
This PR updates the file paths defined in the `files` property of each exercise's `.meta/config.json` file according to the file patterns defined in the track's `config.json` file.
We only update a file path in the `.meta/config.json` file if:
- The file path pattern is a non-empty array in the `config.json` file
- The file path pattern is either not set or an empty array in the `.meta/config.json` file
This means that exercises that had already defined files in the `.meta/config.json` won't be touched in this PR.
Note that this PR is just an easy way for tracks to …

🤖 Sync exercise files keys based on file path patterns

---

config.json
exercises/practice/accumulate/.meta/config.json
exercises/practice/acronym/.meta/config.json
exercises/practice/all-your-base/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/binary-search/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/change/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/isogram/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/minesweeper/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/protein-translation/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/resistor-color/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/two-fer/.meta/config.json
exercises/practice/word-count/.meta/config.json

In this PR, we created (empty) stub files for all exercises that didn't yet have them.
The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.
The original discussion for this is at exercism/discussions#238.
Closes #84
**We will automatically merge this PR in two week's time if it has not been merged by track maintainers at that point :slightly_smiling_face:**
https://github.com/exercism/v3-launch/issues/33

🤖 Add stub files to all exercises

---

exercises/practice/hello-world/src/HelloWorld.re

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

config.json

As explained here: https://github.com/exercism/exercism/issues/6701

Fix copy on compiler notes

---

config.json
exercises/practice/list-ops/.docs/instructions.md
exercises/practice/list-ops/.meta/config.json
exercises/practice/list-ops/.meta/src/Example.re
exercises/practice/list-ops/.meta/tests.toml
exercises/practice/list-ops/__tests__/ListOps_test.re
exercises/practice/list-ops/bsconfig.json
exercises/practice/list-ops/package-lock.json
exercises/practice/list-ops/package.json
exercises/practice/list-ops/src/ListOps.rei

This adds the exercise for [48in24](https://forum.exercism.org/t/48in24-exercise-02-20-list-ops/9805/15)

Add List Ops practice exercise

---

config.json
exercises/practice/knapsack/.docs/instructions.md
exercises/practice/knapsack/.docs/introduction.md
exercises/practice/knapsack/.meta/config.json
exercises/practice/knapsack/.meta/src/Example.re
exercises/practice/knapsack/.meta/tests.toml
exercises/practice/knapsack/__tests__/Knapsack_test.re
exercises/practice/knapsack/bsconfig.json
exercises/practice/knapsack/package-lock.json
exercises/practice/knapsack/package.json
exercises/practice/knapsack/src/Item.re
exercises/practice/knapsack/src/Knapsack.re
exercises/practice/knapsack/src/Knapsack.rei

This is one of the [48in24 exercises](https://forum.exercism.org/t/48in24-exercise-08-13-knapsack/12054).

Add Knapsack exercise

---

config.json
exercises/practice/flower-field/.docs/instructions.md
exercises/practice/flower-field/.docs/introduction.md
exercises/practice/flower-field/.meta/config.json
exercises/practice/flower-field/.meta/src/Example.re
exercises/practice/flower-field/.meta/tests.toml
exercises/practice/flower-field/__tests__/FlowerField_test.re
exercises/practice/flower-field/bsconfig.json
exercises/practice/flower-field/package-lock.json
exercises/practice/flower-field/package.json
exercises/practice/flower-field/src/FlowerField.rei

https://forum.exercism.org/t/suggestion-deprecate-minesweeper-for-flower-field/17967/18

Add `flower-field`
